# Not really used right now but if we ever do some auto-generation/verification
# of things then we can use travis for that.

language: bash

services:
  - docker
  
matrix:
  include:
  - os: linux
    arch: amd64
  - os: linux
    dist: xenial
    virt: lxd
    group: edge
    arch: arm64-graviton2
    
before_install:

script:
  tools/verify-all.sh
